# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='person@example.com', max_length=50),
            preserve_default=False,
        ),
    ]
